In [1]:
x = 1

In [2]:
type(x)

int

In [3]:
x = 1.0

In [4]:
type(x)

float

In [5]:
x = float(1)

In [6]:
type(x)

float

In [7]:
x = 1j
type(x)

complex

In [8]:
x = complex(2)

In [9]:
x

(2+0j)

In [2]:
long = 1


In [13]:
x 

(2+0j)

In [15]:
x = 2 ** 64
x

18446744073709551616

In [17]:
print('"A Question?"')

"A Question?"


In [18]:
#Slicing String
text = "Python strings are sliceable."

In [19]:
text[0]

'P'

In [20]:
text[10]

'i'

In [21]:
l= len(text)

In [23]:
text[l-1]

'.'

In [24]:
text[:10]

'Python str'

In [25]:
text[10:]

'ings are sliceable.'

In [26]:
text[0:2:4]

'P'

In [27]:
text[1:2:3]

'y'

In [28]:
text[-1]

'.'

In [29]:
text[-10]

's'

In [30]:
text = "piush"

In [31]:
text[-1]

'h'

In [32]:
text[0:5:1]

'piush'

In [33]:
text[0:5:2]

'puh'

In [34]:
x = []

In [35]:
type(x)

list

In [36]:
x = [1,2,3,4]
x

[1, 2, 3, 4]

In [37]:
x = [0,1,2,3,4,5]
x[0]

0

In [38]:
x[-1]

5

In [45]:
x[-6:6]

[0, 1, 2, 3, 4, 5]

In [46]:
x=[[1,2,3,4],[5,6,7,8]]

In [47]:
x

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [48]:
x[0]

[1, 2, 3, 4]

In [49]:
x[1]

[5, 6, 7, 8]

In [54]:
x[1][-4:-1]

[5, 6, 7]

In [55]:
#page 38
x = [0,1,2,3,4,5]
#append a value at the end of the list
x.append(6)

In [56]:
x

[0, 1, 2, 3, 4, 5, 6]

In [57]:
#length of the list
len(x)

7

In [58]:
#appends the values in list to the existing list
x.extend([8,9,10])

In [59]:
x

[0, 1, 2, 3, 4, 5, 6, 8, 9, 10]

In [62]:
#removes the value in index position
x.pop(0)

0

In [64]:
x

[2, 4, 5, 6, 8, 9, 10]

In [65]:
#remove the first occurence
x.remove(2)

In [66]:
x

[4, 5, 6, 8, 9, 10]

In [71]:
#delete the element in slice
del x[0]

In [72]:
x

[6, 8, 9]

In [73]:
y = tuple(x)

In [74]:
type(y)

tuple

In [75]:
y

(6, 8, 9)

In [76]:
x = ([1,2],[3,4])

In [77]:
x

([1, 2], [3, 4])

In [78]:
x[0][1] = 10

In [79]:
x

([1, 10], [3, 4])

In [81]:
x = range(10)

In [82]:
type(x)

range

In [83]:
print(x)

range(0, 10)


In [84]:
list(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [85]:
x = range(3,10)

In [86]:
list(x)

[3, 4, 5, 6, 7, 8, 9]

In [87]:
y = list(range(10))

In [88]:
type(y)

list

In [89]:
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
data = {'age': 34,'children': [1,2], 1:'apple'}

In [91]:
data

{1: 'apple', 'children': [1, 2], 'age': 34}

In [92]:
type(data)

dict

In [93]:
data['age']

34

In [94]:
data['age'] = 'xyz'

In [95]:
data

{1: 'apple', 'children': [1, 2], 'age': 'xyz'}

In [96]:
data['name'] = 'piush'

In [97]:
data

{1: 'apple', 'children': [1, 2], 'age': 'xyz', 'name': 'piush'}

In [98]:
del data['age']

In [99]:
data

{1: 'apple', 'children': [1, 2], 'name': 'piush'}

In [2]:
#array is like a list
x = [0.0,1,2,3,4]
x

[0.0, 1, 2, 3, 4]

In [3]:
y = array(x)

NameError: name 'array' is not defined

In [4]:
import numpy
y = array(x)

NameError: name 'array' is not defined

In [5]:
y

NameError: name 'y' is not defined

In [6]:
import numpy as np

In [7]:
y = np.array(x)

In [8]:
y

array([ 0.,  1.,  2.,  3.,  4.])

In [9]:
type(y)

numpy.ndarray

In [11]:
y = np.array([[0.0,1,2,3,4],[5,6,7,8,9]])

In [12]:
y

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

In [14]:
np.shape(y)

(2, 5)

In [3]:
import numpy as np
x = [0,1,2,3,4]

In [4]:
y = np.array(x)

In [5]:
y.dtype

dtype('int32')

In [6]:
y = np.array(x,dtype="float64")

In [7]:
y.dtype

dtype('float64')

In [9]:
y = np.array(x,dtype=np.float64)

In [10]:
y.dtype

dtype('float64')

In [1]:
x = [0,1,2,3,4] #integers

Matrices are essentially a subset of arrays, and behave in a virtually identical manner. The two important
differences are:
• Matrices always have 2 dimensions
• Matrices follow the rules of linear algebra

In [4]:
import numpy as np
x =[0.0,1,2,3,4] # any float makes all float
y = np.array(x)
type(y)

numpy.ndarray

In [5]:
y * y

array([  0.,   1.,   4.,   9.,  16.])

In [7]:
z = np.asmatrix(x)
type(z)

numpy.matrixlib.defmatrix.matrix

In [8]:
z *z

ValueError: shapes (1,5) and (1,5) not aligned: 5 (dim 1) != 1 (dim 0)

In [9]:
x = np.array([[1,2,3,4,5]])
x

array([[1, 2, 3, 4, 5]])

In [11]:
np.ndim(x)

2

In [13]:
x = np.matrix([[1],[2],[3],[4],[5]])

In [14]:
x

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

In [5]:
import numpy as np
x = np.array

In [9]:
#concatenation
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.concatenate((x,y),axis = 0)
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
z = np.concatenate((x,y),axis = 1)
z

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])